### ISSUE TITLE
Need help with installing DSMotion.

### ISSUE THREAD

**Issue by Edmond-Luu** [OperationNT414C/DSMotion#1]
Hello there! I have been trying to install DSMotion but I don't quite understand the instructions. I have already downloaded both the dsmotion.skprx and dsmotion.suprx files. For the config.txt. I am not sure where to edit it. I have attached my config.txt file here. Please help and also remind me if there are nay steps I am missing other than these too. Thank you very much! 
[config.txt](https://github.com/OperationNT414C/DSMotion/files/1240903/config.txt)

**Comment by ghost** [comment]
[config(all).txt](https://github.com/OperationNT414C/DSMotion/files/1241013/config.all.txt)
[config(uncharted).txt](https://github.com/OperationNT414C/DSMotion/files/1241015/config.uncharted.txt)

Here are 2 examples. Config(all) is enabling plugin in every game, and in menu. Should work fine, but in rare cases can cause problems
Config(uncharted) is enabling plugin only for uncharted game. You can edit it with your own game (change PCSA00029 to other game id).

You need to rename them to config.txt to make them work. I hope this example help you understand how taiHEN plugins config file work.

**Comment by Edmond-Luu** [comment]
Thank you so much! It worked! Also, I have another question, if I am adding another plugin, like FakeCamera, do I just add the plugin name right next to the one you added? An example is also appreciated!

**Comment by OperationNT414C** [comment]
Thank you kozarovv for your reply!

Vidalizer, FakeCamera is a userland plugin therefore, it should be added under a title ID section or the "*ALL" section. If you choose the second option and you use "config(all).txt" from kozarovv, you must modify it like this:
```
*ALL
ux0:tai/dsmotion.suprx
ux0:tai/fakecamera.suprx
```

**Comment by Edmond-Luu** [comment]
Thanks OperationNT414C for the help!

I have edited the config.txt to incorporate the FakeCamera plugin ([config.txt](https://github.com/OperationNT414C/DSMotion/files/1247163/config.txt)
) and I also downloaded the actual plugin (fakecamera.suprx) and moved it into ux0:tai folder. To test this, I installed Tearaway and when I started the game, this is an error that I got: 
![2017-08-23-145304](https://user-images.githubusercontent.com/26613209/29640364-83c0f44c-8813-11e7-82c8-32268a0f0a3c.jpg) I'm not sure if what I did caused this or not. Please look in to it. Thanks!

**Comment by OperationNT414C** [comment]
Your "config.txt" file is absolutly not clean: it contains duplicated modules load ("henkaku.suprx" from "ux0:app/MLCL00001/" and from "ur0:tai/") and you put both "dsmotion.suprx" and "fakecamera.suprx" on the same line (so "fakecamera.suprx" is not loaded).

**Comment by awdrifter** [comment]
Please add support for Gravity Rush. Thanks.

**Comment by OperationNT414C** [comment]
Gravity Rush is already supported.

**Comment by Edmond-Luu** [comment]
Thanks OperationNT414C, I fixed the issue with the lines and I got Tearaway working properly. I'm not sure how to fix the other issue, but it doesn't seem like it has any affect.

**Comment by OperationNT414C** [comment]
You welcome.
As long as you don't have duplicated plugins located in both pathes, it should not cause issue but it is simply not "clean".

**Comment by theolux** [comment]
Hi,
I installed DSMotion according to the instructions and I just can't get it to work (trying it on Uncharted) with my DS4. I double checked everything many times and I'm just feeling hopeless by now. On DS4Windows the gyroscope signals seem perfect. What could it possibly be? Is there any way in which I can properly test if DSMotion runs and works at all without playing the same section in Uncharted over and over again...?
Thanks.

**Comment by Edmond-Luu** [comment]
I did this a long ago. I don't remember how I did it. Sorry.

**Comment by theolux** [comment]
Oh... OperationNT414C can you help me out?
I literally double checked everything 10 times by now and tried various things but I just can't get it to work on Uncharted with my DS4 for some reason (haven't tried any other game yet, and I don't have any other DS controllers)

**Comment by OperationNT414C** [comment]
Hello thelox,
Can you provide me your config file?

**Comment by theolux** [comment]
Hi,
I tried both configs that kozarovv posted (renamed to config.txt properly).

**Comment by OperationNT414C** [comment]
Are you sure pathes from the config you copied matches pathes where you copied "DSMotion.skprx" and "DSMotion.suprx"?

**Comment by theolux** [comment]
Absolutely, I put them in ux0:/tai properly and double checked everything multiple times...
Weird right? I just tested Tearaway with fakecamera and that plugin apears to work just fine as the game doesn't crash but when I got to the 'shake it' part I couldn't progress as DSMotion doesn't appear to work on it either... :/
What could it be?

**Comment by theolux** [comment]
@OperationNT414C So you can't help me with that? :/

**Comment by OperationNT414C** [comment]
Sorry but I have no clue. You put the "DSMotion.skprx" under "*KERNEL" section AND "DSMotion.suprx" under "*ALL" section? Your config file has multiple times "*KERNEL" or "*ALL" lines? Do you have plugins which would imply changing mount pathes (SD2Vita, usbmc, ...)?

**Comment by OperationNT414C** [comment]
@theolux https://github.com/OperationNT414C/DSMotion/issues/3
Someone reported that plugin load order seems to matter (and DSMotion kernel plugin must be loaded after NoNpDrm for example). Maybe it is the problem you met?

**Comment by lmaguina** [comment]
> 
> 
> Gravity Rush is already supported.

It doesn't work with the Japanese version (Gravity Daze) . Thanks for the plugin by the way.
