### ISSUE TITLE
Need Help getting dsmotion working with PCSA00029 NoNPDRM on 3.73 h-encore

### ISSUE THREAD

**Issue by the-math-god** [OperationNT414C/DSMotion#7]
hi i've been having a hard time getting this plugin to work on my uncharted golden abyss dump
and i can't figure it out made the correct config changes as you instructed did a proper dump of the game and it still doesn't work heres all the info you need

Game ver. V1.03
Controller. DS4
Firmware. 3.73 h-encore
my config so you can look at it
http://www.mediafire.com/file/naxae7hpmscss1j/config.txt

please help me figure this out

**Comment by OperationNT414C** [comment]
Hello,
dsmotion.skprk => dsmotion.skprx

**Comment by the-math-god** [comment]
made the change still no luck any ideas

**Comment by OperationNT414C** [comment]
There is also an undocumented limitation: if the controller is activated before the kernel plugin initialization, DSMotion won't work. But it can be easily by-passed simply by shutting down the controller and turning it on again.
Maybe this is the issue you are meeting?

**Comment by the-math-god** [comment]
i got it working thanks for the help man
